import { createTool } from '@mastra/core/tools';
import { emailIRAnalyst } from '../../agents/email-ir-analyst';
import { EmailIRCanvasSchema } from '../../schemas/email-ir';
import { riskAssessmentOutputSchema } from './risk-assessment';
import { createLogContext, loggerReporting, logStepStart, logStepComplete, logStepError } from './logger-setup';
import { withRetry } from '../../utils/core/resilience-utils';

export const reportingTool = createTool({
    id: 'email-ir-reporting-tool',
    description: 'Generates Final Canvas JSON Report',
    inputSchema: riskAssessmentOutputSchema,
    outputSchema: EmailIRCanvasSchema,
    execute: async ({ context }) => {
        const inputData = context;
        const emailId = inputData.original_email.from?.split('@')[0] || 'unknown-sender';
        const ctx = createLogContext(emailId, 'reporting');

        try {
            logStepStart(loggerReporting, ctx, { risk_level: inputData.risk_level });

            const prompt = `
# Task: Incident Response Reporting

You are a **Senior Incident Response Analyst**.
Your goal is to synthesize the provided analysis data into a professional Executive Report.

## DATA CONTEXT
**Subject**: "${inputData.original_email.subject}"
**Sender**: "${inputData.original_email.from}"

**Full Analysis Data**:
- **Triage Result**: ${JSON.stringify(inputData.triage_result)}
- **Feature Extraction**: ${JSON.stringify(inputData.feature_result)}
- **Risk Assessment**: Level ${inputData.risk_level} (${inputData.justification})

## IMPORTANT NOTES
- **Blast Radius**: Assume 1 user affected (Targeted) for this report as logic is mocked.
- **Transparency**: Explicitly state that this report was generated by an AI Analyst.

## REPORTING INSTRUCTIONS

Generate the Output Schema based on the analysis above:

1.  **agent_determination**: Write a concise Executive Summary. State the verdict clearly and explain *why* based on the evidence found in Triage and Features.
2.  **remediation_steps**: Specific, actionable steps appropriate for the identified Threat Category and Risk Level.
3.  **investigation_log**: Briefly summarize the logical flow of your analysis.
`;

            const result = await withRetry(
                () => emailIRAnalyst.generate(prompt, {
                    output: EmailIRCanvasSchema,
                }),
                'reporting-llm'
            );

            logStepComplete(loggerReporting, ctx, { report_generated: true });

            return result.object;
        } catch (error) {
            logStepError(loggerReporting, ctx, error as Error);
            throw error;
        }
    }
});
