// Generate app texts with all necessary keys
export function getAppTexts(lang: string) {
  const texts: any = {
    en: {
      loading: "Loading…",
      languageNotFound: "Language not found",
      scrollHint: "Scroll down",
      nextSection: "Next section",
      achievementNotification: "Achievement unlocked 🎉",
      closeNotification: "Close notification",
      startLabel: "Start",
      completedLabel: "Completed",
      progressLabel: "completed",
      points: "points",
      popularLanguages: "Popular languages",
      toggleButtonLightMode: "Switch to light mode",
      toggleButtonDarkMode: "Switch to dark mode",
      hintTitle: "Dark/Light theme",
      hintDescription: "Use the moon/sun icon in the top-right to change your theme",
      surveySubmittedToast: "Thanks for your feedback!"
    },
    tr: {
      loading: "Yükleniyor…",
      languageNotFound: "Dil bulunamadı",
      scrollHint: "Aşağı kaydır",
      nextSection: "Sonraki bölüm",
      achievementNotification: "Başarı kazanıldı 🎉",
      closeNotification: "Bildirimi kapat",
      startLabel: "Başla",
      completedLabel: "Tamamlandı",
      progressLabel: "tamamlandı",
      points: "puan",
      popularLanguages: "Popüler diller",
      toggleButtonLightMode: "Açık temaya geç",
      toggleButtonDarkMode: "Koyu temaya geç",
      hintTitle: "Koyu/Açık tema",
      hintDescription: "Temanızı değiştirmek için sağ üstteki ay/güneş simgesini kullanın",
      surveySubmittedToast: "Geri bildiriminiz için teşekkürler!"
    },
    fr: {
      loading: "Chargement…",
      languageNotFound: "Langue introuvable",
      scrollHint: "Faire défiler vers le bas",
      nextSection: "Section suivante",
      achievementNotification: "Succès débloqué 🎉",
      closeNotification: "Fermer la notification",
      startLabel: "Démarrer",
      completedLabel: "Terminé",
      progressLabel: "terminé",
      points: "points",
      popularLanguages: "Langues populaires",
      toggleButtonLightMode: "Passer au mode clair",
      toggleButtonDarkMode: "Passer au mode sombre",
      hintTitle: "Thème sombre/clair",
      hintDescription: "Utilisez l'icône lune/soleil en haut à droite pour changer de thème",
      surveySubmittedToast: "Merci pour vos commentaires!"
    },
    es: {
      loading: "Cargando…",
      languageNotFound: "Idioma no encontrado",
      scrollHint: "Desplazar hacia abajo",
      nextSection: "Siguiente sección",
      achievementNotification: "¡Logro desbloqueado 🎉",
      closeNotification: "Cerrar notificación",
      startLabel: "Iniciar",
      completedLabel: "Completado",
      progressLabel: "completado",
      points: "puntos",
      popularLanguages: "Idiomas populares",
      toggleButtonLightMode: "Cambiar a modo claro",
      toggleButtonDarkMode: "Cambiar a modo oscuro",
      hintTitle: "Tema oscuro/claro",
      hintDescription: "Usa el ícono de luna/sol en la esquina superior derecha para cambiar tu tema",
      surveySubmittedToast: "¡Gracias por tu comentario!"
    },
    de: {
      loading: "Laden…",
      languageNotFound: "Sprache nicht gefunden",
      scrollHint: "Nach unten scrollen",
      nextSection: "Nächster Abschnitt",
      achievementNotification: "Erfolg freigeschaltet 🎉",
      closeNotification: "Benachrichtigung schließen",
      startLabel: "Starten",
      completedLabel: "Abgeschlossen",
      progressLabel: "abgeschlossen",
      points: "Punkte",
      popularLanguages: "Beliebte Sprachen",
      toggleButtonLightMode: "Zum hellen Modus wechseln",
      toggleButtonDarkMode: "Zum dunklen Modus wechseln",
      hintTitle: "Dunkles/Helles Design",
      hintDescription: "Verwenden Sie das Mond-/Sonnen-Symbol oben rechts, um Ihr Design zu ändern",
      surveySubmittedToast: "Vielen Dank für Ihr Feedback!"
    },
    it: {
      loading: "Caricamento…",
      languageNotFound: "Lingua non trovata",
      scrollHint: "Scorri verso il basso",
      nextSection: "Sezione successiva",
      achievementNotification: "Risultato sbloccato 🎉",
      closeNotification: "Chiudi notifica",
      startLabel: "Inizia",
      completedLabel: "Completato",
      progressLabel: "completato",
      points: "punti",
      popularLanguages: "Lingue popolari",
      toggleButtonLightMode: "Passa al modo chiaro",
      toggleButtonDarkMode: "Passa al modo scuro",
      hintTitle: "Tema scuro/chiaro",
      hintDescription: "Usa l'icona luna/sole in alto a destra per cambiare il tema",
      surveySubmittedToast: "Grazie per il tuo feedback!"
    },
    pt: {
      loading: "Carregando…",
      languageNotFound: "Idioma não encontrado",
      scrollHint: "Rolar para baixo",
      nextSection: "Próxima seção",
      achievementNotification: "Conquista desbloqueada 🎉",
      closeNotification: "Fechar notificação",
      startLabel: "Iniciar",
      completedLabel: "Concluído",
      progressLabel: "concluído",
      points: "pontos",
      popularLanguages: "Idiomas populares",
      toggleButtonLightMode: "Mudar para modo claro",
      toggleButtonDarkMode: "Mudar para modo escuro",
      hintTitle: "Tema escuro/claro",
      hintDescription: "Use o ícone lua/sol no canto superior direito para alterar seu tema",
      surveySubmittedToast: "Obrigado pelo seu feedback!"
    },
    zh: {
      loading: "加载中…",
      languageNotFound: "未找到语言",
      scrollHint: "向下滚动",
      nextSection: "下一部分",
      achievementNotification: "成就解锁 🎉",
      closeNotification: "关闭通知",
      startLabel: "开始",
      completedLabel: "已完成",
      progressLabel: "已完成",
      points: "积分",
      popularLanguages: "热门语言",
      toggleButtonLightMode: "切换到浅色模式",
      toggleButtonDarkMode: "切换到深色模式",
      hintTitle: "深色/浅色主题",
      hintDescription: "使用右上角的月亮/太阳图标来更改主题",
      surveySubmittedToast: "感谢您的反馈！"
    }
  };

  return texts[lang] || texts.en;
}

// Generate app aria texts
export function getAppAriaTexts(lang: string, topic: string) {
  const texts: any = {
    en: {
      appLabel: `${topic} awareness training`,
      appDescription: `Helps you recognize ${topic} threats and report them safely. Interactive microlearning with scenarios and quizzes.`,
      loadingLabel: "Loading content",
      headerLabel: "App title",
      logoLabel: "App logo",
      progressLabel: "Training progress",
      pointsLabel: "Total points earned",
      pointsDescription: "earned points",
      themeToggleDescription: "Switch between light and dark themes",
      languageSelectorLabel: "Language selector",
      languageSelectorDescription: "Select your preferred language for the app",
      languageListLabel: "Available languages",
      languageListDescription: "List of available languages",
      languageSearchDescription: "Search by language name or country code",
      contentLabel: "Training content",
      contentDescription: "Scrollable area with interactive learning modules",
      achievementLabel: "Achievement notification",
      quizCompletionLabel: "Quiz completion hint",
      scrollToTopLabel: "Scroll to top"
    },
    tr: {
      appLabel: `${topic} farkındalık eğitimi`,
      appDescription: `${topic} tehditlerini tanımanıza ve güvenle raporlamanıza yardımcı olur. Senaryolar ve testlerle interaktif mikro-öğrenme.`,
      loadingLabel: "İçerik yükleniyor",
      headerLabel: "Uygulama başlığı",
      logoLabel: "Uygulama logosu",
      progressLabel: "Eğitim ilerlemesi",
      pointsLabel: "Toplam kazanılan puan",
      pointsDescription: "kazanılan puan",
      themeToggleDescription: "Açık ve koyu temalar arasında geçiş yapın",
      languageSelectorLabel: "Dil seçici",
      languageSelectorDescription: "Uygulama için tercih ettiğiniz dili seçin",
      languageListLabel: "Mevcut diller",
      languageListDescription: "Mevcut dillerin listesi",
      languageSearchDescription: "Dil adı veya ülke kodu ile arama yapın",
      contentLabel: "Eğitim içeriği",
      contentDescription: "İnteraktif öğrenme modülleri ile kaydırılabilir alan",
      achievementLabel: "Başarı bildirimi",
      quizCompletionLabel: "Test tamamlama ipucu",
      scrollToTopLabel: "Üste kaydır"
    },
    fr: {
      appLabel: `Formation de sensibilisation ${topic}`,
      appDescription: `Vous aide à reconnaître les menaces ${topic} et à les signaler en toute sécurité. Micro-apprentissage interactif avec scénarios et quiz.`,
      loadingLabel: "Chargement du contenu",
      headerLabel: "Titre de l'application",
      logoLabel: "Logo de l'application",
      progressLabel: "Progression de la formation",
      pointsLabel: "Total des points gagnés",
      pointsDescription: "points gagnés",
      themeToggleDescription: "Basculer entre les thèmes clair et sombre",
      languageSelectorLabel: "Sélecteur de langue",
      languageSelectorDescription: "Sélectionnez votre langue préférée pour l'application",
      languageListLabel: "Langues disponibles",
      languageListDescription: "Liste des langues disponibles",
      languageSearchDescription: "Rechercher par nom de langue ou code pays",
      contentLabel: "Contenu de formation",
      contentDescription: "Zone défilante avec modules d'apprentissage interactifs",
      achievementLabel: "Notification de succès",
      quizCompletionLabel: "Indice de fin de quiz",
      scrollToTopLabel: "Défiler vers le haut"
    },
    es: {
      appLabel: `Entrenamiento de concienciación sobre ${topic}`,
      appDescription: `Te ayuda a reconocer las amenazas de ${topic} y reportarlas de forma segura. Microaprendizaje interactivo con escenarios y cuestionarios.`,
      loadingLabel: "Cargando contenido",
      headerLabel: "Título de la aplicación",
      logoLabel: "Logo de la aplicación",
      progressLabel: "Progreso del entrenamiento",
      pointsLabel: "Total de puntos ganados",
      pointsDescription: "puntos ganados",
      themeToggleDescription: "Cambiar entre temas claro y oscuro",
      languageSelectorLabel: "Selector de idioma",
      languageSelectorDescription: "Selecciona tu idioma preferido para la aplicación",
      languageListLabel: "Idiomas disponibles",
      languageListDescription: "Lista de idiomas disponibles",
      languageSearchDescription: "Buscar por nombre de idioma o código de país",
      contentLabel: "Contenido del entrenamiento",
      contentDescription: "Área desplazable con módulos de aprendizaje interactivos",
      achievementLabel: "Notificación de logro",
      quizCompletionLabel: "Pista de finalización del cuestionario",
      scrollToTopLabel: "Desplazar hacia arriba"
    },
    de: {
      appLabel: `${topic} Awareness-Training`,
      appDescription: `Hilft Ihnen dabei, ${topic}-Bedrohungen zu erkennen und sicher zu melden. Interaktives Microlearning mit Szenarien und Quiz.`,
      loadingLabel: "Inhalt laden",
      headerLabel: "App-Titel",
      logoLabel: "App-Logo",
      progressLabel: "Trainingsfortschritt",
      pointsLabel: "Gesamte verdiente Punkte",
      pointsDescription: "verdiente Punkte",
      themeToggleDescription: "Zwischen hellen und dunklen Designs wechseln",
      languageSelectorLabel: "Sprachauswahl",
      languageSelectorDescription: "Wählen Sie Ihre bevorzugte Sprache für die App",
      languageListLabel: "Verfügbare Sprachen",
      languageListDescription: "Liste der verfügbaren Sprachen",
      languageSearchDescription: "Nach Sprachname oder Ländercode suchen",
      contentLabel: "Trainingsinhalt",
      contentDescription: "Scrollbarer Bereich mit interaktiven Lernmodulen",
      achievementLabel: "Erfolgsbenachrichtigung",
      quizCompletionLabel: "Quiz-Abschlusshinweis",
      scrollToTopLabel: "Nach oben scrollen"
    },
    it: {
      appLabel: `Formazione di sensibilizzazione ${topic}`,
      appDescription: `Ti aiuta a riconoscere le minacce ${topic} e a segnalarle in sicurezza. Microapprendimento interattivo con scenari e quiz.`,
      loadingLabel: "Caricamento contenuto",
      headerLabel: "Titolo dell'app",
      logoLabel: "Logo dell'app",
      progressLabel: "Progresso della formazione",
      pointsLabel: "Punti totali guadagnati",
      pointsDescription: "punti guadagnati",
      themeToggleDescription: "Passa tra temi chiaro e scuro",
      languageSelectorLabel: "Selettore lingua",
      languageSelectorDescription: "Seleziona la tua lingua preferita per l'app",
      languageListLabel: "Lingue disponibili",
      languageListDescription: "Elenco delle lingue disponibili",
      languageSearchDescription: "Cerca per nome lingua o codice paese",
      contentLabel: "Contenuto formazione",
      contentDescription: "Area scorrevole con moduli di apprendimento interattivi",
      achievementLabel: "Notifica risultato",
      quizCompletionLabel: "Suggerimento completamento quiz",
      scrollToTopLabel: "Scorri in alto"
    },
    pt: {
      appLabel: `Treinamento de conscientização sobre ${topic}`,
      appDescription: `Ajuda você a reconhecer ameaças de ${topic} e reportá-las com segurança. Microaprendizado interativo com cenários e quizzes.`,
      loadingLabel: "Carregando conteúdo",
      headerLabel: "Título do aplicativo",
      logoLabel: "Logo do aplicativo",
      progressLabel: "Progresso do treinamento",
      pointsLabel: "Total de pontos ganhos",
      pointsDescription: "pontos ganhos",
      themeToggleDescription: "Alternar entre temas claro e escuro",
      languageSelectorLabel: "Seletor de idioma",
      languageSelectorDescription: "Selecione seu idioma preferido para o aplicativo",
      languageListLabel: "Idiomas disponíveis",
      languageListDescription: "Lista de idiomas disponíveis",
      languageSearchDescription: "Pesquisar por nome do idioma ou código do país",
      contentLabel: "Conteúdo do treinamento",
      contentDescription: "Área rolável com módulos de aprendizado interativos",
      achievementLabel: "Notificação de conquista",
      quizCompletionLabel: "Dica de conclusão do quiz",
      scrollToTopLabel: "Rolar para o topo"
    },
    zh: {
      appLabel: `${topic} 意识培训`,
      appDescription: `帮助您识别 ${topic} 威胁并安全报告。带有场景和测验的互动微学习。`,
      loadingLabel: "加载内容",
      headerLabel: "应用标题",
      logoLabel: "应用图标",
      progressLabel: "培训进度",
      pointsLabel: "总获得积分",
      pointsDescription: "获得积分",
      themeToggleDescription: "在浅色和深色主题之间切换",
      languageSelectorLabel: "语言选择器",
      languageSelectorDescription: "选择应用的首选语言",
      languageListLabel: "可用语言",
      languageListDescription: "可用语言列表",
      languageSearchDescription: "按语言名称或国家代码搜索",
      contentLabel: "培训内容",
      contentDescription: "带有互动学习模块的可滚动区域",
      achievementLabel: "成就通知",
      quizCompletionLabel: "测验完成提示",
      scrollToTopLabel: "滚动到顶部"
    }
  };

  return texts[lang] || texts.en;
}